version: "3.3"

services:
  suprb:
    image: kennethreitz/httpbin
    container_name: suprb
    ports:
      - "8090:80"
    # Update with real application
    networks:
      - internal-network

  nginx:
    # image: nginx:1.17.0-alpine # ToDo remove build
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      # - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/nginx-automation/nginx/:/etc/nginx/
      - /opt/acme:/opt/acme
      - /opt/acme-certs:/opt/acme-certs
    ports:
      - 80:80
      - 443:443
    networks:
      - internal-network

  cert-manager:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: cert-manager
    volumes:
      # - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/nginx-automation/nginx/:/var/www/nginx/
      - /opt/acme:/opt/acme
      - /opt/acme-certs:/opt/acme-certs
    ports:
      - 5000:5000
    networks:
      - internal-network

networks:
  internal-network: